config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 4, maximum: 100 }
    validates :description, presence: true, length: { minimum: 6, maximum: 1000000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                            uniqueness: { case_sensitive: false }, 
                            length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                            uniqueness: { case_sensitive: false }, 
                            length: { maximum: 105 },
                            format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(whitelist)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(whitelist)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:notice] = "Article was delete successfully"
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def whitelist
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own articles"
            redirect_to @article
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:show, :index]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(whitelist)
        if @category.save
            flash[:notice] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def show
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)    
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
        if @category.update(whitelist)
            flash[:notice] = "Category name was updated successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def destroy
        @category.destroy
        flash[:notice] = "Category was delete successfully"
        redirect_to categories_path
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def whitelist
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins perform that action"
            redirect_to categories_path
        end
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to root_path
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You are now logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(whitelist)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog, #{@user.username}. Your account has been successfully created."
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(whitelist)
            flash[:notice] = "Your account information was updated successfully"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to root_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def whitelist
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, size = 80)
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_src, alt: "#{user.username}`s profile picture", class: "rounded shadow mx-auto d-block")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center" id="article">
            <div class="col-12 mt-4">
                <div class="card text-center shadow-sm">
                  <div class="card-header font-italic">
                        <% if article.user %>
                            by <%= link_to article.user.username, user_path(article.user) %>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <% if article.categories.any? %>
                            <div class="mb-3"><%= render article.categories %></div> 
                        <% end %>    
                        <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 160) %></p>
                        <%= link_to 'View', article_path(article), class: "btn btn-outline-primary" %>
                        <% if logged_in? && (article.user == current_user || current_user.admin? == true) %>
                            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-primary" %>
                            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary" %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Posted <%= time_ago_in_words(article.created_at) %> ago, 
                    edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                  </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-8">
        <%= render 'shared/errors', obj: @article %>
        <%= form_with(model: @article, local: true) do |f| %>

            <div class="mb-3 row">
                <%= f.label :title, class: "form-label" %>
                <%= f.text_field :title, class: "form-control shadow-sm", placeholder: "Enter your title" %>
            </div>

            <div class="mb-3 row">
                <%= f.label :description, class: "form-label" %></br>
                <%= f.text_area :description, rows: 10, class: "form-control shadow-sm", placeholder: "Enter your description" %>
            </div>

            <div class="mb-3 row">
                <%= f.label "Choose categories below", class: "form-label" %></br>
                <%= f.collection_select(:category_ids, Category.all, :id, :name,
                { prompt: nil}, { multiple: true, size: Category.count, class: "custom-select shadow-sm" }) %>
            </div>

            <div class="mb-3 row justify-content-center" id="full-btn">
                    <%= f.submit nil, class: "btn btn-primary btn-lg shadow-sm" %>
            </div>

            <%= link_to 'Cancel and return to all articles', articles_path, class: "row justify-content-center" %>

        <% end %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Articles listing page</h1>
<%= render 'articles' %>
<div class="flickr_pagination mt-4 <%= @articles.count > 5 ? "mb-4" : "" %>">
    <%= will_paginate @articles, :container => false %>
</div>
<% if logged_in? %>
    <div class="container">
        <div class="row justify-content-center" id="new-btn">
            <div class="col-12" id="full-btn">
                <%= link_to 'New article', new_article_path, class: "btn btn-primary btn-lg" %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container big-container" id="article-show-container">
    <div class="row justify-content-center">
        <div class="col-12 card p-4 shadow-sm" id="article">
            <article class="blog-post">
                <% if @article.categories.any? %>
                    <div class="mb-3"><%= render @article.categories %></div> 
                <% end %>
                <h2 class="blog-post-title"><%= @article.title %></h2>
                <p class="blog-post-meta">Posted <%= time_ago_in_words(@article.created_at) %> ago by <a href=<%= user_path(@article.user) %>><%= @article.user.username if @article.user %></a></p>
                <p><%= simple_format(@article.description) %></p>
                <% if logged_in? && (@article.user == current_user || current_user.admin? == true) %>
                    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-primary" %>
                    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary" %>
                <% end %>
            </article>
        </div>
    </div>
    <%= link_to 'Return to all articles', articles_path, class: "row justify-content-center mt-4" %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true) do |f| %>

    <div class="mb-3 row">
        <%= f.label :name, "Category name", class: "form-label" %>
        <%= f.text_field :name, class: "form-control shadow-sm", placeholder: "Choose category name" %>
    </div>

    <div class="mb-3 row justify-content-center" id="full-btn">
            <%= f.submit "Create category", class: "btn btn-primary btn-lg shadow-sm" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category</h1>
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-8">
        <%= render 'form' %>

            <%= link_to 'Cancel and return to category', @category, class: "row justify-content-center" %>

        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center">Categories</h1>

<div class="container" id="categories-container">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center" id="article">
            <div class="col-12 mt-4">
                <div class="card text-center shadow-sm">
                  <div class="card-body">
                    <h5 class="card-title mt-3"><%= link_to category.name, category %></h5>
                    <p class="card-text mt-2"><%= pluralize(category.articles.count, "article") %></p>
                  </div>
                  <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(category.created_at) %> ago</small>
                  </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="flickr_pagination mt-4 <%= @categories.count > 5 ? "mb-4" : "" %>">
        <%= will_paginate @users, :container => false %>
    </div>
</div>
<% if logged_in? && current_user.admin? %>
    <div class="container" id="categories-container">
        <div class="row justify-content-center" id="new-btn">
            <div class="col-12" id="full-btn">
                <%= link_to 'New category', new_category_path, class: "btn btn-primary btn-lg" %>
            </div>
        </div>
    </div>
<% end %>

app/views/categories/new.html.erb
<h1 class="text-center">Create category</h1>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-8">
        <%= render 'shared/errors', obj: @category %>
        <%= form_with(model: @category, local: true) do |f| %>

            <div class="mb-3 row">
                <%= f.label :name, "Category name", class: "form-label" %>
                <%= f.text_field :name, class: "form-control shadow-sm", placeholder: "Choose category name" %>
            </div>

            <div class="mb-3 row justify-content-center" id="full-btn">
                    <%= f.submit "Create category", class: "btn btn-primary btn-lg shadow-sm" %>
            </div>

            <%= link_to 'Cancel and return to all categories', @category, class: "row justify-content-center" %>

        <% end %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mb-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? == true %>
    <div class="text-center mt-4">
        <%= link_to 'Edit category', edit_category_path(@category), class: "btn btn-outline-primary btn-lg" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Related articles</h3>

<%= render 'articles/articles' %>

<div class="flickr_pagination mt-4 <%= @articles.count > 5 ? "mb-4" : "" %>">
    <%= will_paginate @articles, :container => false %>
</div>

<% if logged_in? && current_user.admin? == true %>
    <div class="row">
        <div class="col-12 text-center justify-content-center">
            <%= link_to 'Delete category', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-muted mb-4" %>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Copyright &copy <%= link_to "Sophie Bonneval", "http://sophiebonneval.com/", class: "text-muted" %></span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>    
    <div class="row justify-content-center" id="messages">
        <div class="col-12" id="message">
            <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Sophie Bonneval", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "All articles", articles_path, class: "nav-link" %>
                <%= link_to "Articles by Category", categories_path, class: "nav-link" %>
                <div class="dropdown-divider"></div>
                <%= link_to "New article", new_article_path, class: "nav-link" %>
                <% if logged_in? && current_user.admin? %>
                <%= link_to "New category", new_category_path, class: "nav-link" %>
                <% end %>
              </div>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Articles", articles_path, class: "nav-link" %>
            </li>
        <% end %>
        <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <ul class="navbar-nav mr-auto">
            <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "View your profile", user_path(current_user), class: "nav-link" %>
                        <%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-link" %>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link">-</a>
                </li>
                <li class="nav-item">
                    <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
                </li>
            <% else %>
                <li class="nav-item ml-3">
                    <%= link_to "Github", "https://github.com/Maldorana", class: "btn btn-primary" %>
                </li>
            <% end %>
        </ul>
      </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">About</h1>
<div class="container mt-4" id="about-container">
    <div class="jumbotron bg-white card shadow-sm text-center">
      <h1 class="display-4">Hello, world!</h1>
      <p class="lead">This blog is my first Ruby on Rails project.</p>
      <hr class="my-4">
      <p>To see more of my work, click on the button below:</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="http://sophiebonneval.com/" target="_blank" role="button">My portfolio</a>
      </p>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container big-container" id="home-container">
    <div class="p-4 p-md-5 mb-2 text-white rounded bg-dark">
    <div class="col-md-8 px-0">
      <h1 class="display-4 fst-italic"><%= Article.find(1).title %></h1>
      <p class="lead my-3"><%= truncate(Article.find(1).description, length: 180) %></p>
      <a role="button" href="<%= article_path(Article.find(1)) %>" class="btn btn-primary">Continue reading</a>    
    </div>
    </div>
    <div class="row">
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mt-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static bg-white">
              <h3 class="mb-0"><%= Article.find(2).title %></h3>
              <div class="mb-1 text-muted"><%= time_ago_in_words(Article.find(2).created_at) %> ago</div>
              <p class="card-text mb-auto"><%= truncate(Article.find(2).description, length: 180) %></p>
              <a href="<%= article_path(Article.find(2)) %>" class="stretched-link">Continue reading...</a>
            </div>
            <div class="col-auto d-none d-lg-block" style="width: 200px; height: 250px; overflow: hidden">
              <img src="https://images.unsplash.com/photo-1504639725590-34d0984388bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1267&q=80" height="100%" align="middle" alt="">
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mt-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static bg-white">
              <h3 class="mb-0"><%= Article.find(3).title %></h3>
              <div class="mb-1 text-muted"><%= time_ago_in_words(Article.find(3).created_at) %> ago</div>
              <p class="mb-auto"><%= truncate(Article.find(3).description, length: 180) %></p>
              <a href="<%= article_path(Article.find(3)) %>" class="stretched-link">Continue reading...</a>
            </div>
            <div class="col-auto d-none d-lg-block" style="width: 200px; height: 250px; overflow: hidden">
                <img src="https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" height="100%" align="middle" alt="">
            </div>
          </div>
        </div>
        </div>
        <div class="row">
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mt-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static bg-white">
              <h3 class="mb-0"><%= Article.find(4).title %></h3>
              <div class="mb-1 text-muted"><%= time_ago_in_words(Article.find(4).created_at) %> ago</div>
              <p class="card-text mb-auto"><%= truncate(Article.find(4).description, length: 180) %></p>
              <a href="<%= article_path(Article.find(4)) %>" class="stretched-link">Continue reading...</a>
            </div>
            <div class="col-auto d-none d-lg-block" style="width: 200px; height: 250px; overflow: hidden">
                <img src="https://images.unsplash.com/photo-1546146830-2cca9512c68e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80" height="100%" align="left" alt="">
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mt-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static bg-white">
              <h3 class="mb-0"><%= Article.find(5).title %></h3>
              <div class="mb-1 text-muted"><%= time_ago_in_words(Article.find(5).created_at) %> ago</div>
              <p class="mb-auto"><%= truncate(Article.find(5).description, length: 180) %></p>
              <a href="<%= article_path(Article.find(5)) %>" class="stretched-link">Continue reading...</a>
            </div>
            <div class="col-auto d-none d-lg-block" style="width: 200px; height: 250px; overflow: hidden">
                <img src="https://images.unsplash.com/photo-1542831371-29b0f74f9713?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1740&q=80" height="100%" align="left" alt="">
            </div>
          </div>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> to be saved:</h4>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-8">
        <%= render 'shared/errors', obj: @user %>
        <%= form_with(model: @user, local: true) do |f| %>

            <div class="mb-3 row">
                <%= f.label :username, class: "form-label" %>
                <%= f.text_field :username, class: "form-control shadow-sm", placeholder: "Choose your username" %>
            </div>

            <div class="mb-3 row">
                <%= f.label :email, class: "form-label" %></br>
                <%= f.email_field :email, class: "form-control shadow-sm", placeholder: "Enter your email address" %>
            </div>

            <div class="mb-3 row">
                <%= f.label :password, class: "form-label" %></br>
                <%= f.password_field :password, class: "form-control shadow-sm", placeholder: "Choose your password" %>
            </div>

            <div class="mb-3 row justify-content-center" id="full-btn">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update profile", class: "btn btn-primary btn-lg shadow-sm") %>
            </div>

            <%= link_to 'Cancel and return to profile', @user, class: "row justify-content-center" %>

        <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">Alpha Bloggers</h1>

<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center" id="article">
            <div class="col-12 mt-4">
                <div class="card text-center shadow-sm">
                  <div class="card-header font-italic">
                    <%= link_to user.username, user %>
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, 100), user %>
                    </h5>
                    <p class="card-text mt-2 font-weight-bold"><%= pluralize(user.articles.count, "article") %></p>
                    <%= link_to 'View profile', user, class: "btn btn-outline-primary" %>
                    <% if logged_in? && (user == current_user || current_user.admin? == true) %>
                        <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-primary" %>
                    <% end %>
                  </div>
                  <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                  </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="flickr_pagination mt-4 <%= @users.count > 5 ? "mb-4" : "" %>">
        <%= will_paginate @users, :container => false %>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Create your account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mb-4"> <%= @user.username %></h1>

<%= gravatar_for(@user, 150) %>

<% if logged_in? && (@user == current_user || current_user.admin? == true) %>
    <div class="text-center mt-4">
        <%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-outline-primary btn-lg" %>
    </div>
<% end %>

<h3 class="text-center mt-4"> <%= @user.username %>'s articles</h3>

<%= render 'articles/articles' %>

<div class="flickr_pagination mt-4 <%= @articles.count > 5 ? "mb-4" : "" %>">
    <%= will_paginate @articles, :container => false %>
</div>

<% if logged_in? && (@user == current_user || current_user.admin? == true) %>
    <div class="row">
        <div class="col-12 text-center justify-content-center">
            <%= link_to 'Delete account and all articles', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-muted mb-4" %>
        </div>
    </div>
<% end %>